/**
 * Concept cards the question generator binds against.
 * Locators are grounded in jev-elder/DIGEST.md or the 2026-09-19 enterprise atlas.
 */

export type Access = "open" | "application" | "commercial" | "synthetic";

export interface ConceptCard {
  id: string;
  name: string;
  sector: string;
  problem: string;
  gold: string;
  proxy: string;
  locator: string;
  metric: string;
  instrument: string;
  access: Access;
  temporal: boolean;
}

export const CONCEPTS: ConceptCard[] = [
  {
    id: "doctrine-color",
    name: "JEV interface color",
    sector: "doctrine",
    problem: "Type a port before composition",
    gold: "internal operad of a live agent harness",
    proxy: "manutej/jev colors.ts",
    locator: "https://github.com/manutej/jev",
    metric: "color-mismatch refusal rate",
    instrument: "colored operad γ",
    access: "open",
    temporal: false,
  },
  {
    id: "doctrine-mask",
    name: "Masked-language port fill",
    sector: "doctrine",
    problem: "Fill [MASK] only with an allowed color",
    gold: "production tool-call guardrail",
    proxy: "src/lib/jev/corpus.ts MaskItem",
    locator: "https://github.com/manutej/jev",
    metric: "Brier vs gold color",
    instrument: "scoreFill + toxin mass",
    access: "open",
    temporal: false,
  },
  {
    id: "doctrine-fail-closed",
    name: "Fail-closed gate",
    sector: "doctrine",
    problem: "Do not ship on toxin or mid-band",
    gold: "irreversible / money human gate",
    proxy: "src/lib/jev/score.ts",
    locator: "https://github.com/manutej/jev",
    metric: "false-GREEN rate on toxin fixtures",
    instrument: "τ_green=0.72 τ_toxin=0.12 τ_red=0.4",
    access: "open",
    temporal: false,
  },
  {
    id: "pjm-lmp",
    name: "PJM locational marginal price",
    sector: "energy",
    problem: "Nodal price / congestion nowcast under renewable and data-center shocks",
    gold: "ISO private telemetry + desk book",
    proxy: "PJM Data Miner 2 RT hourly LMP",
    locator: "https://dataminer2.pjm.com/feed/rt_hrl_lmps/definition",
    metric: "pinball / CRPS on spike tails",
    instrument: "neural SDE + conformal intervals",
    access: "open",
    temporal: true,
  },
  {
    id: "caiso-oasis",
    name: "CAISO OASIS",
    sector: "energy",
    problem: "Bay Area / CAISO day-ahead vs real-time spread",
    gold: "scheduling coordinator private awards",
    proxy: "CAISO OASIS public reports",
    locator: "http://oasis.caiso.com",
    metric: "pinball on DA-RT spread",
    instrument: "graph net on nodes + conformal",
    access: "open",
    temporal: true,
  },
  {
    id: "nrel-wind",
    name: "NREL WIND Toolkit",
    sector: "energy",
    problem: "Weather-to-power scenarios for unit commitment",
    gold: "plant SCADA + ISO forecast",
    proxy: "NREL WIND Toolkit 126k sites",
    locator: "https://www.nrel.gov/grid/wind-toolkit.html",
    metric: "reserve vs shortage cost",
    instrument: "flow matching scenarios + two-stage UC",
    access: "open",
    temporal: true,
  },
  {
    id: "cmapss-rul",
    name: "NASA C-MAPSS RUL",
    sector: "manufacturing",
    problem: "Remaining useful life under regime shift",
    gold: "OEM onboard health + shop-visit dollars",
    proxy: "NASA C-MAPSS / N-CMAPSS",
    locator: "https://data.nasa.gov/Aerospace/CMAPSS-Jet-Engine-Simulated-Data/ff5v-kuh6",
    metric: "RUL interval coverage by cycle bucket",
    instrument: "deep survival + conformal RUL",
    access: "open",
    temporal: true,
  },
  {
    id: "bosch-line",
    name: "Bosch production line",
    sector: "manufacturing",
    problem: "Escaped-defect vs inspection budget on sparse stations",
    gold: "live MES + costed scrap",
    proxy: "Kaggle Bosch Production Line Performance",
    locator: "https://www.kaggle.com/c/bosch-production-line-performance",
    metric: "inspection-budget vs escaped-defect curve",
    instrument: "station GNN + conformal reject",
    access: "open",
    temporal: true,
  },
  {
    id: "mvtec-ad",
    name: "MVTec industrial anomaly",
    sector: "manufacturing",
    problem: "Unsupervised visual inspection",
    gold: "line-side labeled defects + recall cost",
    proxy: "MVTec AD",
    locator: "https://www.mvtec.com/company/research/datasets/mvtec-ad",
    metric: "pixel-AUROC + calibrated anomaly score",
    instrument: "diffusion / VLM few-shot + conformal",
    access: "open",
    temporal: false,
  },
  {
    id: "wm811k",
    name: "WM811K wafer maps",
    sector: "manufacturing",
    problem: "Yield pattern → process tool",
    gold: "fab yield war-room traces",
    proxy: "MIR-WM811K / LSWMD",
    locator: "https://github.com/jonathanwvd/awesome-industrial-datasets",
    metric: "semi-supervised pattern F1 vs labeled-only",
    instrument: "PU learning + persistent homology",
    access: "open",
    temporal: false,
  },
  {
    id: "salt-erp",
    name: "SAP SALT linked tables",
    sector: "enterprise-tabular",
    problem: "Multi-table sales autocompletion on sparse ERP",
    gold: "customer SAP landscape",
    proxy: "Hugging Face SAP/SALT",
    locator: "https://huggingface.co/datasets/SAP/SALT",
    metric: "exact-match under 43% sparsity",
    instrument: "relational GNN / RelBench",
    access: "open",
    temporal: true,
  },
  {
    id: "ais-vessel",
    name: "USCG / NOAA AIS",
    sector: "logistics",
    problem: "Port-pair ETA and dark-route anomaly",
    gold: "carrier AIS vendor + bookings",
    proxy: "Marine Cadastre AIS 2009–2025",
    locator: "https://marinecadastre.gov/ais/",
    metric: "ETA MAE + anomaly precision@k",
    instrument: "neural CDE / trajectory transformer",
    access: "open",
    temporal: true,
  },
  {
    id: "faf-freight",
    name: "BTS Freight Analysis Framework",
    sector: "logistics",
    problem: "Multimodal shock propagation",
    gold: "shipper-level TMS",
    proxy: "BTS FAF5/FAF6",
    locator: "https://www.bts.gov/faf",
    metric: "tonnage/value residual vs 2021–22 disruptions",
    instrument: "graph optimal transport",
    access: "open",
    temporal: true,
  },
  {
    id: "fmcsa-crash",
    name: "FMCSA carrier crash",
    sector: "logistics",
    problem: "Carrier risk for insurance and routing",
    gold: "insurer triangle + broker win history",
    proxy: "FMCSA MCMIS crash file",
    locator: "https://data.transportation.gov/Trucking-and-Motorcoaches/Crash-File/aayw-vxb3",
    metric: "90-day crash conformal coverage",
    instrument: "hierarchical Bayes + conformal",
    access: "open",
    temporal: true,
  },
  {
    id: "tabred",
    name: "TabReD industrial tabular",
    sector: "enterprise-tabular",
    problem: "Tabular models under temporal drift",
    gold: "internal feature store with time splits",
    proxy: "Yandex TabReD",
    locator: "https://github.com/yandex-research/tabred",
    metric: "rank reversal random vs time split",
    instrument: "GBDT vs tabular FM + ADWIN",
    access: "open",
    temporal: true,
  },
  {
    id: "mimic-iv",
    name: "MIMIC-IV deterioration",
    sector: "healthcare",
    problem: "ICU deterioration alarms without nurse fatigue",
    gold: "multi-hospital EHR + billing",
    proxy: "PhysioNet MIMIC-IV",
    locator: "https://physionet.org/content/mimiciv/",
    metric: "lead-time vs false-page conformal bound",
    instrument: "neural SDE + conformal risk control",
    access: "application",
    temporal: true,
  },
];

export function conceptById(id: string): ConceptCard | undefined {
  return CONCEPTS.find((c) => c.id === id);
}
